# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-01 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recipe_id', models.CharField(max_length=100)),
                ('recipe_url', models.URLField()),
                ('recipe_nickname', models.CharField(max_length=100)),
            ],
        ),
    ]
